<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    <Configurations>Debug;Release;AzureUAT</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.24.0" />
    <PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="4.0.1" />
    <PackageReference Include="Microsoft.Graph" Version="5.58.0" />
    <PackageReference Include="TypeGen" Version="3.0.0" />
    <PackageReference Include="TypeScriptModelsGenerator" Version="1.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BLH.ApproveIQ.API\BLH.ApproveIQ.API.csproj" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="dotnet &quot;$(MSBuildThisFileDirectory)../Sparkhound.CodeGenerator/bin/$(Configuration)/net8.0/Sparkhound.CodeGenerator.dll&quot;" />
  </Target>
</Project>