<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BLH.ApproveIQ.Domain</RootNamespace>
    <Configurations>Debug;Release;AzureUAT</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.24.0" />
    <PackageReference Include="MediatR" Version="11.0.0" />
    <PackageReference Include="Microsoft.Graph" Version="5.58.0" />
    <PackageReference Include="NPOI" Version="2.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Identity\Services\" />
  </ItemGroup>
</Project>